// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: albums.sql

package db

import (
	"context"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO
    albums (title, artist, price)
VALUES ($1, $2, $3) RETURNING id,
    title,
    artist,
    price
`

type CreateAlbumParams struct {
	Title  string `json:"title"`
	Artist string `json:"artist"`
	Price  string `json:"price"`
}

type CreateAlbumRow struct {
	ID     int32  `json:"id"`
	Title  string `json:"title"`
	Artist string `json:"artist"`
	Price  string `json:"price"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (CreateAlbumRow, error) {
	row := q.queryRow(ctx, q.createAlbumStmt, createAlbum, arg.Title, arg.Artist, arg.Price)
	var i CreateAlbumRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Price,
	)
	return i, err
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM albums WHERE id = $1
`

func (q *Queries) DeleteAlbum(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.deleteAlbumStmt, deleteAlbum, id)
	return err
}

const getAlbumByID = `-- name: GetAlbumByID :one
SELECT id, title, artist, price FROM albums WHERE id = $1
`

type GetAlbumByIDRow struct {
	ID     int32  `json:"id"`
	Title  string `json:"title"`
	Artist string `json:"artist"`
	Price  string `json:"price"`
}

func (q *Queries) GetAlbumByID(ctx context.Context, id int32) (GetAlbumByIDRow, error) {
	row := q.queryRow(ctx, q.getAlbumByIDStmt, getAlbumByID, id)
	var i GetAlbumByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Price,
	)
	return i, err
}

const getAlbums = `-- name: GetAlbums :many
SELECT id, title, artist, price
FROM albums
ORDER BY id
LIMIT $1
OFFSET
    $2
`

type GetAlbumsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetAlbumsRow struct {
	ID     int32  `json:"id"`
	Title  string `json:"title"`
	Artist string `json:"artist"`
	Price  string `json:"price"`
}

func (q *Queries) GetAlbums(ctx context.Context, arg GetAlbumsParams) ([]GetAlbumsRow, error) {
	rows, err := q.query(ctx, q.getAlbumsStmt, getAlbums, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlbumsRow
	for rows.Next() {
		var i GetAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbum = `-- name: UpdateAlbum :one
UPDATE albums
SET
    title = $2,
    artist = $3,
    price = $4
WHERE
    id = $1 RETURNING id,
    title,
    artist,
    price
`

type UpdateAlbumParams struct {
	ID     int32  `json:"id"`
	Title  string `json:"title"`
	Artist string `json:"artist"`
	Price  string `json:"price"`
}

type UpdateAlbumRow struct {
	ID     int32  `json:"id"`
	Title  string `json:"title"`
	Artist string `json:"artist"`
	Price  string `json:"price"`
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (UpdateAlbumRow, error) {
	row := q.queryRow(ctx, q.updateAlbumStmt, updateAlbum,
		arg.ID,
		arg.Title,
		arg.Artist,
		arg.Price,
	)
	var i UpdateAlbumRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Price,
	)
	return i, err
}
