// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Album struct {
	ID        int32        `json:"id"`
	Title     string       `json:"title"`
	Artist    string       `json:"artist"`
	Price     string       `json:"price"`
	CreatedAt sql.NullTime `json:"created_at"`
}
